# Generated by Django 5.0.1 on 2024-01-19 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adhar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Allot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Adhar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.adhar')),
            ],
        ),
    ]
